# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/Lab 9-10/Lab 9-10.cache/wt} [current_project]
set_property parent.project_path {E:/Lab 9-10/Lab 9-10.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo {e:/Lab 9-10/Lab 9-10.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/Add_sub.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/imports/src/D_FF.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/imports/new/Decoder_2_to_4.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/imports/new/Decoder_3_to_8.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/imports/src/FA.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/imports/src/HA.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/Instruction_decoder.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/imports/src/LUT_16_7.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/MUX_2way_3bit.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/MUX_2way_4bit.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/MUX_8_to_1.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/imports/Downloads/ProgramROM.VHD}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/Program_Counter.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/imports/src/Reg.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/Reg_DFF.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/imports/src/Reg_bank.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/Reg_seg.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/imports/src/Slow_Clk.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/TBA.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/display_unit.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/tri_state_buffer_3bit.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/tri_state_buffer_4bit.vhd}
  {E:/Lab 9-10/Lab 9-10.srcs/sources_1/new/Nanoprocessor.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/Lab 9-10/Lab 9-10.srcs/constrs_1/new/nanoprocessor_xdc.xdc}}
set_property used_in_implementation false [get_files {{E:/Lab 9-10/Lab 9-10.srcs/constrs_1/new/nanoprocessor_xdc.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Nanoprocessor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Nanoprocessor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Nanoprocessor_utilization_synth.rpt -pb Nanoprocessor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
